blank_issues_enabled: false
contact_links:
  - name: SemiClaw Documentation
    url: https://github.com/vagawind/semiclaw/blob/main/docs/QA.md
    about: Check SemiClaw FAQ
  - name: Discussions
    url: https://github.com/vagawind/semiclaw/discussions
    about: Ask questions or share ideas in Discussions
